/**
 * @description Algoritmo de Cesar para cifrar/decifrar.
 * @param {String} texto Es la cadena de texto ingresada por el usuario.
 * @param {String} accion Indica lla acción cifrar descifrar.
 * @author Brenda Yasmin Barrios Becerra
 * @returns {String} Resultado segun la acción indicada.
 */

function cesar(texto, accion){
    let mensajeCifrado="";
    let arreglo={
        'a':'x',
        'b':'y',
        'c':'z',
        'd':'a',
        'e':'b',
        'f':'c',
        'g':'d',
        'h':'e',
        'i':'f',
        'j':'g',
        'k':'h',
        'l':'i',
        'm':'j',
        'n':'k',
        'ñ':'l',
        'o':'m',
        'p':'n',
        'q':'ñ',
        'r':'o',
        's':'p',
        't':'q',
        'u':'r',
        'v':'s',
        'w':'t',
        'x':'u',
        'y':'v',
        'z':'w',
        'A':'X',
        'B':'Y',
        'C':'Z',
        'D':'A',
        'E':'B',
        'F':'C',
        'G':'D',
        'H':'E',
        'I':'F',
        'J':'G',
        'K':'H',
        'L':'I',
        'M':'J',
        'N':'K',
        'Ñ':'L',
        'O':'M',
        'P':'N',
        'Q':'Ñ',
        'R':'O',
        'S':'P',
        'T':'Q',
        'U':'R',
        'V':'S',
        'W':'T',
        'X':'U',
        'Y':'V',
        'Z':'W',

        ' ':' ',
        
    }
    let arreglo2={
        'x': 'a',
        'y': 'b',
        'z': 'c',
        'a': 'd',
        'b': 'e',
        'c': 'f',
        'd': 'g',
        'e': 'h',
        'f': 'i',
        'g': 'j',
        'h': 'k',
        'i': 'l',
        'j': 'm',
        'k': 'n',
        'l': 'ñ',
        'm': 'o',
        'n': 'p',
        'ñ': 'q',
        'o': 'r',
        'p': 's',
        'q': 't',
        'r': 'u',
        's': 'v',
        't': 'w',
        'u': 'x',
        'v': 'y',
        'w': 'z',
        'X': 'A',
        'Y': 'B',
        'Z': 'C',
        'A': 'D',
        'B': 'E',
        'C': 'F',
        'D': 'G',
        'E': 'H',
        'F': 'I',
        'G': 'J',
        'H': 'K',
        'I': 'L',
        'J': 'M',
        'K': 'N',
        'L': 'Ñ',
        'M': 'O',
        'N': 'P',
        'Ñ': 'Q',
        'O': 'R',
        'P': 'S',
        'Q': 'T',
        'R': 'U',
        'S': 'V',
        'T': 'W',
        'U': 'X',
        'V': 'Y',
        'W': 'Z',
        ' ': ' ',

        
    }
    for (let letra of texto){
        if(accion=='cifrar')
        mensajeCifrado+=arreglo[letra];
        else mensajeCifrado+=arreglo2[letra];
    }

    return mensajeCifrado;
}